CREATE TABLE STUDENT (SNUM INTEGER NOT NULL, SNAME VARCHAR(10) NOT NULL, DEPTID INTEGER NOT NULL, SLEVEL VARCHAR(20) NOT NULL, AGE INTEGER NOT NULL);
CREATE TABLE CLASS ( CNAME VARCHAR(10) NOT NULL, MEETS_AT DATE NOT NULL, ROOM VARCHAR(10) NOT NULL, FID INTEGER NOT NULL);
CREATE TABLE ENROLLED ( SNUM INTEGER NOT NULL, CNAME VARCHAR(10) NOT NULL);
CREATE TABLE FACULTY ( FID INTEGER NOT NULL, FNAME VARCHAR(10) NOT NULL, DEPTID INTEGER NOT NULL);
CREATE TABLE DEPARTMENT (DEPTID INTEGER NOT NULL, DNAME VARCHAR(30) NOT NULL, LOCATION VARCHAR(30) NOT NULL);
